### ISSUE TITLE
Survey editing

### ISSUE THREAD

**Issue by wasade** [biocore/american-gut-web#257]
Needs to source from `survey_answers` and `survey_answers_other` and populate the survey with responses. This should reuse as much of the existing survey handlers as possible. In the best case, there is a link that `POST`s to the survey handler, and everything proceeds the same as you would if you came from the consent form.

**Comment by squirrelo** [comment]
This is completed using the survey object and handlers now, correct?

**Comment by wasade** [comment]
Yes. Sorry, should have closed this a while back.
