### ISSUE TITLE
Document how to run tests

### ISSUE THREAD

**Issue by beaugunderson** [biocore/american-gut-web#334]
Moving this into its own issue.

Looking for guidance on how to setup and run the test suite. It looks like it's hardcoded to use a database called "ag_test" but I don't know how it should be created or if it should be pre-initialized with anything.

`python setup.py test` seems like it's the actual runner but let me know if that's incorrect.

@wasade Just looking for some quick guidance here so that I can ensure I'm not breaking anything with my changes (and also help with updating Tornado to a newer version).

cc: @madprime @jasonbobe

**Comment by beaugunderson** [comment]
How's the test suite doing? I saw #434 about adding Travis so it seems like some work has been done; when I try to run the test suite locally via `python setup.py test` or `tox` it starts the first test and then begins to rebuild the test database, the first step of which is to `DROP SCHEMA IF EXISTS ag CASCADE` which seems to never make any progress (I checked using `pg_top` and it just shows it in state `waiting`).

cc @squirrelo

**Comment by squirrelo** [comment]
We have no tests that work right now. Once the test database is confirmed working, I'll work on getting Travis set up and removing any old tests that are in the system. Once Travis is working, we can start adding tests back in.
