### ISSUE TITLE
KeyError on "name" in portal

### ISSUE THREAD

**Issue by wasade** [biocore/american-gut-web#349]
```python
    Traceback (most recent call last):
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1332, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 2607, in wrapper
        return method(self, *args, **kwargs)
      File "/home/qiita/american_gut/amgut/handlers/portal.py", line 14, in get
        user_name = user_info['name']
    KeyError: 'name'
```

**Comment by wasade** [comment]
@squirrelo, did you get a chance to test the credentials on this?

**Comment by squirrelo** [comment]
It worked for me. Not sure whats up but couldn't reproduce it.

**Comment by wasade** [comment]
That's been the fun with this issue: reproducing it. ugh.

**Comment by wasade** [comment]
_might_ be a browser issue. can you try putting the lock down on browser
security settings? and/or try an obscure browser? note, much of the ag web
stuff is behind with respect to improvements made with qiita, so any odd
browser issues we encountered there may be relevant here.

**Comment by squirrelo** [comment]
I've had issues with uBlock and other script blockers screwing up the javascript and not actually allowing a submit button to work. That could be the case here too.

**Comment by wasade** [comment]
Just a note, this is still a present issue

**Comment by wasade** [comment]
@squirrelo, I looked closer at this as the issue is still prevalent. Some how the user is able to issue an authorized GET against `portal`, triggering a cascade of issues including that `sitebase.html` assumes `supplied_kit_id` exists. 

Looking further through the logic, shouldn't this [line](https://github.com/biocore/american-gut-web/blob/master/amgut/handlers/auth_handlers.py#L48) issue a `self.set_current_user(skid)` instead of the secure cookie? What I'm wondering is why the logic here for "logging in" differs from what happens when you actually login, particularly as I suspect the resulting issue stems from this [line](https://github.com/biocore/american-gut-web/blob/master/amgut/handlers/portal.py#L13).

**Comment by squirrelo** [comment]
Yeah, this is something we probably want to disuss in the meeting on the first: Currently we are storing the SKID, but really we should be storing  the ag_login_id when a user logs in. 

The issue I think stems from the fact that we log in, then check for registering the kit, then do other things. I am going to mess with the logic order in the login function and see if I can fix this issue. Good catch.

**Comment by wasade** [comment]
I _think_ all we need to do is just self.set_current_user following handout
registration, right?

**Comment by squirrelo** [comment]
Yes, but there are some other issues with register as well. Namely you are logged in when you get to the register page, and I think this should not be behind the @authenticated wall. This would fix a lot of the problems we are having with registering kits, as you aren't logged in, then logged out, then logged in again.

**Comment by wasade** [comment]
@squirrelo, this is good to close now, right?

**Comment by squirrelo** [comment]
I believe so
