### ISSUE TITLE
"Sequencing & Results" tab does not properly link participants to their results

### ISSUE THREAD

**Issue by elainewolfe** [biocore/american-gut-web#357]
The "Sequencing & Results" tab does not indicate that results are ready even if they have been uploaded. For whatever reason, this works on the test account, but is not working in any participant account I've come across.

**Comment by wasade** [comment]
This issue might be due to this:

```sql
select count(1) from ag.ag_kit_barcodes where survey_id is not null;
 count
-------
   851
(1 row)
```

Not positive though, just adding a note.

**Comment by wasade** [comment]
`ag.ag_kit_barcodes.results_ready` was not set for these kits. This has been addressed in the database.
