### ISSUE TITLE
NOT NULL constraint on ag_login_surveys.participant_name

### ISSUE THREAD

**Issue by adamrp** [biocore/american-gut-web#366]
I think this should be there, but it is not. Is there a reason not to have it? There are currently no participant_names in that table that are NULL.

**Comment by wasade** [comment]
agree. not presently finding any (thankfully) but this likely should go in as a patch

**Comment by wasade** [comment]
@squirrelo, want to just lump this one in with one of the db patches you're already doing? Still not seeing any of these so should just be a matter of adding:

```sql
alter table ag.ag_login_surveys alter column participant_name set not null;
```

**Comment by squirrelo** [comment]
Part of #430 now

**Comment by wasade** [comment]
Thanks!
