### ISSUE TITLE
ag_new_survey_exists in ag_data_access

### ISSUE THREAD

**Issue by adamrp** [biocore/american-gut-web#367]
The name of the function disagrees with the docstring, and both disagree with the implementation. At the time of the creation of this issue, [the lines exist here](https://github.com/biocore/american-gut-web/blob/master/amgut/lib/data_access/ag_data_access.py#L1220-L1229).

The function is use only in labadmin (and there only once), so shouldn't impact the main site directly. Its use in labadmin suggests that the name of the function and the docstring should be updated, but the implementation is correct. The function is intended to check whether or not a barcode is associated with a new survey.

**Comment by squirrelo** [comment]
we also already have the function `is_old_survey` which seems to be more robust.

**Comment by squirrelo** [comment]
Function no longer exists
