### ISSUE TITLE
Changes to GUI needed for UCSD compliance

### ISSUE THREAD

**Issue by ackermag** [biocore/american-gut-web#371]
There is a considerable amount of change that will have to be in place before we can go live with UCSD requirements (assuming we don't have to correct too many things for UCSD IRB) following the review on March 5th.
I can provide the documented changes and the new features we will require before it is approved so that you developers know what is coming.... Would this be helpful?

**Comment by rob-knight** [comment]
Yes, please pass on that info ASAP.


On Feb 20, 2015, at 8:34 PM, ackermag <notifications@github.com<mailto:notifications@github.com>> wrote:


There is a considerable amount of change that will have to be in place before we can go live with UCSD requirements (assuming we don't have to correct too many things for UCSD IRB) following the review on March 5th.
I can provide the documented changes and the new features we will require before it is approved so that you developers know what is coming.... Would this be helpful?

**Comment by wasade** [comment]
Yes, thanks

**Comment by ackermag** [comment]
Is this correct forum for that communication?

On Fri, Feb 20, 2015 at 9:23 PM, Daniel McDonald <notifications@github.com>
wrote:

> Yes, thanks
>
> On Fri, Feb 20, 2015 at 9:57 PM, Rob Knight <notifications@github.com>
> wrote:
>
>
> > Yes, please pass on that info ASAP.
> >
> >
> > On Feb 20, 2015, at 8:34 PM, ackermag <notifications@github.com<mailto:
> > notifications@github.com>> wrote:
> >
> >
> > There is a considerable amount of change that will have to be in place
> > before we can go live with UCSD requirements (assuming we don't have to
> > correct too many things for UCSD IRB) following the review on March 5th.
> > I can provide the documented changes and the new features we will require
> > before it is approved so that you developers know what is coming....
> Would
> > this be helpful?
> >
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/biocore/american-gut-web/issues/371>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/biocore/american-gut-web/issues/371#issuecomment-75356046
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/american-gut-web/issues/371#issuecomment-75356755>
> .
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by wasade** [comment]
Email first please, and we can partition up specific tasks from there.
Please send to qiita-devs

**Comment by ackermag** [comment]
OK - I will take care of this....

On Fri, Feb 20, 2015 at 9:47 PM, Daniel McDonald <notifications@github.com>
wrote:

> Email first please, and we can partition up specific tasks from there.
> Please send to qiita-devs
>
> On Feb 20, 2015 10:44 PM, "ackermag" <notifications@github.com> wrote:
>
> > Is this correct forum for that communication?
> >
> > On Fri, Feb 20, 2015 at 9:23 PM, Daniel McDonald <
> notifications@github.com
> > >
> > wrote:
> >
> > > Yes, thanks
> > >
> > > On Fri, Feb 20, 2015 at 9:57 PM, Rob Knight <notifications@github.com>
> > > wrote:
> > >
> > >
> > > > Yes, please pass on that info ASAP.
> > > >
> > > >
> > > > On Feb 20, 2015, at 8:34 PM, ackermag <notifications@github.com
> > <mailto:
> > > > notifications@github.com>> wrote:
> > > >
> > > >
> > > > There is a considerable amount of change that will have to be in
> place
> > > > before we can go live with UCSD requirements (assuming we don't have
> to
> > > > correct too many things for UCSD IRB) following the review on March
> > 5th.
> > > > I can provide the documented changes and the new features we will
> > require
> > > > before it is approved so that you developers know what is coming....
> > > Would
> > > > this be helpful?
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/biocore/american-gut-web/issues/371>.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/biocore/american-gut-web/issues/371#issuecomment-75356046
> > > >
> > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/biocore/american-gut-web/issues/371#issuecomment-75356755
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Gail Ackermann
> > Knight Lab
> > UCSD
> > glackermann@ucsd.edu <ackermag@ucsd.edu>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/biocore/american-gut-web/issues/371#issuecomment-75357362
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/american-gut-web/issues/371#issuecomment-75357438>
> .
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by wasade** [comment]
@squirrelo, can you close if appropriate please?
