### ISSUE TITLE
ag_authenticate_user procedure needs to be updated via patch

### ISSUE THREAD

**Issue by wasade** [biocore/american-gut-web#372]
This [one](https://github.com/biocore/american-gut-web/blob/master/amgut/lib/data_access/procedures/ag_authenticate_user.sql), the change isn't reflected in a patch so production systems won't see it.

**Comment by wasade** [comment]
@squirrelo @adamrp, i believe this got pulled out into a ag_data access method, right?

**Comment by squirrelo** [comment]
Yes, this is closable.
