### ISSUE TITLE
Improve session expiration

### ISSUE THREAD

**Issue by beaugunderson** [biocore/american-gut-web#391]
Currently a new `COOKIE_SECRET` is chosen each time the server starts, invalidating all previous sessions. From discussions with @wasade it seems that this invalidation can be a barrier to deployment (it logs everyone out and that's undesirable).

One way to solve this is to move `COOKIE_SECRET` to the configuration file. This would allow sessions (which are just persisted in secure cookies) to persist across server restarts. The `COOKIE_SECRET` in the configuration could be changed manually if session invalidation is ever desired.

If this is an acceptable change I'm happy to write a pull request. :)

**Comment by wasade** [comment]
:+1:, thanks @beaugunderson! 

cc @qiita-dev, this approach may be of interest

**Comment by ElDeveloper** [comment]
Yes, I like this idea a lot!

**Comment by squirrelo** [comment]
I'm cool with it.

**Comment by adamrp** [comment]
Makes good sense to me. Security wise, what circumstances would warrant a
cookie secret change?

**Comment by beaugunderson** [comment]
@adamrp If you found a vulnerability that enabled session highjacking that would be an excellent reason to invalidate all existing sessions. :)

**Comment by beaugunderson** [comment]
OK, a simple pull request for this is at #392.
