### ISSUE TITLE
Lat/long/elevation information needs to be per-survey

### ISSUE THREAD

**Issue by adamrp** [biocore/american-gut-web#410]
Right now, it's recorded in the `ag_login` table, but that is not specific enough. Since we ask for current zip code on the survey, we should record this information in a a new table
```sql
create table geocode_lookup (zip varchar primary key, latitude float, longitude float, elevation float)
```
Suggested course of action is to create a patch that
- [ ] Creates the `geocode_lookup` table described above
- [ ] Updates the table with the existing information from the `ag_login` table
```sql
insert into geocode_lookup select zip, latitude, longitude, elevation from ag_login
```

Then:
- [ ] Modify [add_geocoding_info](https://github.com/biocore/american-gut-web/blob/master/amgut/lib/data_access/ag_data_access.py#L624) function to pull zip codes from `survey_answers_other` and add them the new table rather than the `ag_login` table.
- [ ] Modify the labadmin handler for update geocoding
- [ ] Run the geocoding update function through labadmin

**Comment by adamrp** [comment]
Is this really done? Isn't lat/long/elevation actually currently per login?

**Comment by squirrelo** [comment]
Yes, it's now done by zipcode in survey.

**Comment by adamrp** [comment]
Right! thanks.
