### ISSUE TITLE
Email verification is incomplete

### ISSUE THREAD

**Issue by wasade** [biocore/american-gut-web#422]
Am seeing in the error logs an instance of a user specifying "foo&bar.com" and making it through the survey to the end

**Comment by wasade** [comment]
Not sure if we have an easy resolution here. The email is sent following completion of the survey, so we don't actually know if the email address works until we get to the end. I think the best thing we can do is make sure the regex on emails is pretty good.

**Comment by adamrp** [comment]
I think the best code we have for this is currently in in qiita (see the [validate_email](https://github.com/biocore/qiita/blob/f50391230389b7401a2846b2227e0f8bfeb4c18f/qiita_db/user.py#L513-L578) function). I guess we should copy-paste it on over here?
