### ISSUE TITLE
Registering two handout kits to the same email address

### ISSUE THREAD

**Issue by adamrp** [biocore/american-gut-web#471]
If a single person (identified by their email address) registers two handout kits, then the second registration will silently ignore all information they enter on `register_user.html` (since it just calls [`ag_data.addAGLogin`](https://github.com/biocore/american-gut-web/blob/master/amgut/lib/data_access/ag_data_access.py#L139-L154)).

On register_user.html, It would be better just to ask for their email first and then (via AJAX or websocket) check whether they're already in the system before showing them the rest of the registration form.

**Comment by EmbrietteH** [comment]
Closing as this will be addressed when we make the move to Redcap.
