### ISSUE TITLE
./scripts/ag make test fails because build_and_initialize is not called

### ISSUE THREAD

**Issue by beaugunderson** [biocore/american-gut-web#485]
It looks like the recently added `ag_test_patch22.sql.gz` relies on both the `postgres` role and the `ag_wwwuser` role already existing.

In my setup (Postgres.app on OS X) I don't actually have a `postgres` role (I only have a role named with my username) so I think `ag_wwwuser` (or a master `ag` role) should be used instead of postgres for compatibility.

One way would be to run `build_and_initialize` before `populate_test_db` (which might require changes to `build_and_initialize`), another would be to add the creation of the roles to `ag_test_patch22.sql.gz`.

**Comment by wasade** [comment]
I think it would be cleaner to add the creation of the roles.

**Comment by josenavas** [comment]
What about sourcing from the configuration file, since such information is in there?

**Comment by wasade** [comment]
That works as well

**Comment by beaugunderson** [comment]
do you mean using build_and_initialize but taking the names from the configuration file?

---

**Comment by josenavas** [comment]
Yup, this way each developer can have it's own configuration, rather than adopt our configurations to the one in the live system

**Comment by squirrelo** [comment]
the issue there is that the data being dumped in for tests is dependent on the patch number of that data. I'll take a look at what can be done for removing user dependence for the test database. I believe there is a way to dump the database without user permissions settings.
