### ISSUE TITLE
(not urgent) replace any instances of "stealth.openhumans.org" with "www.openhumans.org"

### ISSUE THREAD

**Issue by beaugunderson** [biocore/american-gut-web#550]
I noticed requests from American Gut coming into Open Humans using the hostname `stealth.openhumans.org`, which was used before we launched many months ago. Any references to `stealth.openhumans.org` in the configuration should be updated to `www.openhumans.org`.

This is not currently affecting anything but we don't anticipate keeping that domain around forever; it would be great to wrap it up after @squirrelo is back from vacation.

**Comment by tkosciol** [comment]
the issue has already been fixed in `ag_config.txt` and in `amgut/ag_config.txt`.

**Comment by beaugunderson** [comment]
@tkosciol I think this can be closed then. :)

**Comment by EmbrietteH** [comment]
Thanks @tkosciol ! Closing this issue.
