### ISSUE TITLE
Out-dated FAQ link

### ISSUE THREAD

**Issue by elainewolfe** [biocore/american-gut-web#574]
An automated email is sent out to participants when their samples are scanned in and OK'ed for processing. The email includes a link to the FAQ stating when results will be ready, but the link is out-dated. The old link is http://www.microbio.me/americangut/FAQ.psp#faq4. The new link should be http://microbio.me/AmericanGut/faq/#faq4. The full email sent out is below

"We have recently received your sample with barcode _______ dated ________ and we have begun processing it. Please see our FAQ section for when you can expect results.
(http://www.microbio.me/americangut/FAQ.psp#faq4)"

**Comment by squirrelo** [comment]
Moved to labadmin [#52](https://github.com/biocore/labadmin/issues/52)
