### ISSUE TITLE
Update British Gut portal FAQ

### ISSUE THREAD

**Issue by elainewolfe** [biocore/american-gut-web#584]
https://microbio.me/BritishGut/international_shipping/

The above link is out-of-date. The British Gut is able to accept non-UK European samples at their lab now.

**Comment by AlexanderFengFeng** [comment]
@wasade I had a question about this. I understand that Americans should send to the AG address and UK (and apparently all Europeans) should send to the BG address. So then does that mean all international participants excluding these regions should send to the AG address?

**Comment by AlexanderFengFeng** [comment]
Including this change in the list of changes being made for Dom's suggestions.
