### ISSUE TITLE
Link to FAQ broken

### ISSUE THREAD

**Issue by EmbrietteH** [biocore/american-gut-web#594]
When a sample is received, an auto-email is sent, containing the following link (which gives a 404 error when trying to access): http://www.microbio.me/americangut/FAQ.psp#faq4

**Comment by squirrelo** [comment]
This is fixed in [master for labadmin](https://github.com/biocore/labadmin/blob/master/knimin/handlers/barcode_util.py#L164) so it looks like we just need to deploy the current master for labadmin.

**Comment by EmbrietteH** [comment]
Closing (per above comment).
