### ISSUE TITLE
Need new instruction packet up on website

### ISSUE THREAD

**Issue by BrentKLer** [biocore/american-gut-web#609]
The instructions at https://microbio.me/AmericanGut/static/img/full_instructions.pdf are outdated. Embriette or Elaine have the most recently updated instructions in a .pdf form. 

Cheers,
Brent

**Comment by tkosciol** [comment]
@EmbrietteH could you email me the latest version of those instructions, so that we can update them?

**Comment by AlexanderFengFeng** [comment]
@wasade working on this for dom
