### ISSUE TITLE
ENH: consent page for personal microbiome survey not showing

### ISSUE THREAD

**Issue by EmbrietteH** [biocore/american-gut-web#625]
This was addressed in [this](https://github.com/biocore/american-gut-web/pull/615) PR, but when going to 

https://ag-test.ucsd.edu/amgut-test/authed/secondary_survey/?type=personal_microbiome&participant_name=Embriette%20Hyde 

on the test system (which is deployed and current), the consent verbiage does not appear.

**Comment by wasade** [comment]
Wrong link, wanna try:

https://ag-test.ucsd.edu/amgut-test/authed/personal_microbiome_overview/?participant_name=Embriette%20Hyde

?

**Comment by EmbrietteH** [comment]
Closed as issue has been resolved.
