### ISSUE TITLE
deleteAGParticipantSurvey needs to check if there are surveys to delete

### ISSUE THREAD

**Issue by josenavas** [biocore/american-gut-web#678]
If there are no surveys to delete, this SQL query 

https://github.com/biocore/american-gut-web/blob/6c645603bb5c0b481cfb176b22e7ea8c131bdf21/amgut/lib/data_access/ag_data_access.py#L320-L331

will fail with a syntax error since the issued query will look like

```sql
SELECT barcode
FROM ag.source_barcodes_surveys
WHERE survey_id IN ()
```

**Comment by AlexanderFengFeng** [comment]
Should now check if there are barcodes to delete as well as only add to the consent_removed table if the profile is not currently part of it already.
