### ISSUE TITLE
Boulder address is listed in BG site

### ISSUE THREAD

**Issue by wasade** [biocore/american-gut-web#687]
In the FAQ

**Comment by AlexanderFengFeng** [comment]
Just put out a pull request for this issue

**Comment by AlexanderFengFeng** [comment]
@wasade Also, is all this information still correct?
University of California, San Diego
Knight Lab/ATTN: Greg Humphrey
BRF II Room 1220D
9500 Gilman Drive, MC 0763
La Jolla, CA 92093-0763

**Comment by wasade** [comment]
Yes, thanks!
